nc-news-6
8maziar/be-new-portfolio pull request #5
Opened 2023-06-28 11:26 UTC by 8maziar

2023-06-28 13:39 UTC, Liam310 requested changes
Hey there 👋 

First thing to note: commit messages. Try to phrase your commit messages like you're filling in the blanks of This commit will ____. Avoid using task numbers/descriptions from the challenges we give you, they will have no context for any future prospective employers reading your commit history. A good example might be "add a fetch article by ID endpoint".

There's a ton of great code in here, well done 👏 

Just one thing I'm going to pull you up on - what would happen if I tried to make a request for the comments on an article that had no comments? Currently I think your logic would respond with a 404 not found but... what if we could find the article, it just didn't have any comments? Think about yesterday's lecture and consult the notes if you need an assist.

2023-06-28 13:39 UTC, Liam310 commented on __tests__/app.test.js
> +        expect(comments[0].created_at).toBe("2020-11-03T21:00:00.000Z");
I like the intention here - I think just checking one item might be a little undercooked. I recommend having a look at using [jest-sorted](https://www.npmjs.com/package/jest-sorted) as a tool to help you do this neatly!

2023-06-28 13:39 UTC, Liam310 commented on __tests__/app.test.js
> +
Solid error testing in both cases here!

2023-06-29 09:15 UTC, RichardNeat approved these changes
Nice work implementing that change! All good to merge :)

2023-06-29 11:49 UTC, merged